@startuml

package Anatomy {
    class MuscleGroup {
        MuscleGroup
        Name
        BodySegment
    }

    class Muscle {
        Name
        MuscleGroup
    }

    class BodySegment {
        BodySegment
        Name
    }
    
    BodySegment *--> MuscleGroup
    MuscleGroup *--> Muscle
}

package Fitness {
    class Exercise {
        Name
        + MusclesWorked List<ExerciseMuscleWorked>
        Equipment
    }

    class ExerciseMuscleWorked {
        Muscle
        MuscleWorkedAmount
    }

    enum MuscleWorkedAmount {
        Primary
        Secondary
    }

    Exercise *--> ExerciseMuscleWorked
    ExerciseMuscleWorked --> MuscleWorkedAmount
    ExerciseMuscleWorked o--> Anatomy.Muscle
}

Fitness.Exercise o--> Gymnasium.Equipment

package Training {
    class TrainingProfile {
        Name
    }

    class MacroPeriodization
    {
        TrainingProfile
        DateStartUtc
        DateStartEndUtc
    }

    class MesocyclePeriodization
    {
        CycleOrder        
        CycleLengthUnit
        CycleLengthValue
    }

    class MicroCyclePeriodization
    {
        CycleOrder
        IsDeload        
        Sesssions List<SessionPeriodization>
    }

    class WorkOutSessionPeriodization
    {
        IsRestDay
        Exercises List<Exercise> 
    }

    MacroPeriodization *--> MesocyclePeriodization     
    MesocyclePeriodization *--> MicroCyclePeriodization
    MicroCyclePeriodization *--> WorkOutSessionPeriodization

    class TrainingProfileWeightTracker {
        TrainingProfileId
        RecordDateUtc
        WeightInput decimal(19,4)
        IsInputMetric
        NormalizedWeightKg decimal(19,4)
    }

    class TrainingProfileRole {
        TrainingProfileId
        RoleId
        UserId
    }

    class SessionWork {
        TrainingProfile
        Series List<SeriesWorked>
        + SessionStartDateUtc
    }

    class SeriesWorked {
        Exercise
        Sets List<SetWorked>
    }

    class SetWorked {
        Reps
        Weight
    }

    SessionPeriodization o--> Fitness.Exercise
    TrainingProfileWeightTracker o--> TrainingProfile
    MacroPeriodization o--> TrainingProfile
    TrainingProfile *--> TrainingProfileRole
    SessionWork o--> TrainingProfile
    SessionWork *--> SeriesWorked
    SeriesWorked *--> SetWorked
}

Training.SeriesWorked o--> Fitness.Exercise

package Gymnasium {
    class Venue {
        VenuId
        Name  
        + Address Address      
        + VenueEquipment List<VenueEquipment>
    }

    class VenueEquipment {
        Venu
        Equipment
        Quantity
    }

    class Equipment {
        Name
        EquipmentType
    }

    enum EquipmentType {
        Freewreight
        Machine
        Other
    }
    
    Venue *--> VenueEquipment
    VenueEquipment o--> Equipment
    Equipment --> EquipmentType
}
Venue *--> Common.Address

package Common {
    class Address {
        StreetNumber
        StreeName
        Unit
        PostalCode
        Country
        State
        City
    }
}
@enduml